"""add_project_id_to_messages

Revision ID: 3ae4a0052dc6
Revises: d37c01c6068a
Create Date: 2026-07-05 11:12:12.431196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae4a0052dc6'
down_revision: Union[str, None] = 'd37c01c6068a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_messages_projects', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_projects', type_='foreignkey')
        batch_op.drop_column('project_id')
    # ### end Alembic commands ###
