"""add_is_pinned_to_chat

Revision ID: 3c91db5e5685
Revises: 24673d5373f9
Create Date: 2026-07-05 10:07:33.414717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c91db5e5685'
down_revision: Union[str, None] = '24673d5373f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_pinned')
    # ### end Alembic commands ###
