"""create_projects_and_project_files_tables

Revision ID: 4769f347b1e9
Revises: 3c91db5e5685
Create Date: 2026-07-05 10:58:11.041851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4769f347b1e9'
down_revision: Union[str, None] = '3c91db5e5685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=True),
    sa.Column('repo_owner', sa.String(length=255), nullable=True),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('languages', sa.String(length=512), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=100), nullable=True),
    sa.Column('last_commit_message', sa.String(length=255), nullable=True),
    sa.Column('last_commit_author', sa.String(length=100), nullable=True),
    sa.Column('last_commit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_files')
    op.drop_table('projects')
    # ### end Alembic commands ###
