"""add_intelligence_metadata_to_project_file

Revision ID: d37c01c6068a
Revises: 4769f347b1e9
Create Date: 2026-07-05 11:09:42.524765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37c01c6068a'
down_revision: Union[str, None] = '4769f347b1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('intelligence_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_files', 'intelligence_metadata')
    # ### end Alembic commands ###
