"""create_project_agent_tasks_table

Revision ID: e7efa3456a6c
Revises: e9d24b8f17b3
Create Date: 2026-07-05 17:25:05.874982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7efa3456a6c'
down_revision: Union[str, None] = 'e9d24b8f17b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('issue_content', sa.Text(), nullable=False),
    sa.Column('implementation_plan', sa.Text(), nullable=True),
    sa.Column('proposed_changes', sa.Text(), nullable=True),
    sa.Column('proposed_tests', sa.Text(), nullable=True),
    sa.Column('proposed_docs', sa.Text(), nullable=True),
    sa.Column('pr_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_agent_tasks')
    # ### end Alembic commands ###
